### ISSUE TITLE
Missing file hfi1_user.h

### ISSUE THREAD

**Issue by immaraj** [01org/opa-psm2#36]
I downloaded this release and compiled it successfully using a make command with no arguments. But if I try to compile it with make PSM_CUDA=1 then I get a bunch of errors. It looks like we are missing an update to file named hfi1_user.h with some declarations and defines.
struct hfi1_tid_info_v2 is one of the declarations which appears to be missing in this release of intel/opa-psm2. I appreciate any help regarding this issue.

**Comment by mwheinz** [comment]
Could you paste your build log, please?

**Comment by mwheinz** [comment]
BTW - /usr/include/rdma/hfi/hfi1_user.h is provided by the kernel-headers package.

**Comment by immaraj** [comment]
> BTW - /usr/include/rdma/hfi/hfi1_user.h is provided by the kernel-headers package.

Thanks let me investigate. yes the file that I have in /usr/include/rdma/hfi appears to be an older version. I will have to update that one and rebuild.

**Comment by mwheinz** [comment]
Discussing this internally, I was told you may need to download and install the whole IFS package to get the CUDA support. (This is because nVidia has not chosen to open source their CUDA support forcing us to release the packages as binaries.)

**Comment by ToddRimmer** [comment]
Mentoring: when interacting remotely it can be good to indicate “why” on such questions.  In this case at least part of the reason may be that since nVidia has not open sourced Cuda we can’t upstream our code for Cuda support.

Since this is a github discussion, these folks will often not like responses that point to binary releases.  However in this case nVidia has tied our hands.

Todd Rimmer
DCG Architecture
Voice: 484-245-9487
Todd.Rimmer@intel.com<mailto:Todd.Rimmer@intel.com>

**Comment by immaraj** [comment]
Thanks I am in the process of doing that right now.
Paul

________________________________
